### ISSUE TITLE
直接中文提问了

### ISSUE THREAD

**Issue by sanruby77** [YageGeng/thinkbook16p-gen5-sound-fix#1]
能写个简明的使用的 Readme 吗?在 ubuntu 上编译过后,加载不了显卡驱动,然后然后就没装成功.非常感谢

**Comment by YageGeng** [comment]
你好，这个patch无法解决thinkbook16p gen5的声音问题，他只能解决内核的报错

**Comment by YageGeng** [comment]
Hi, 经过测试内核版本6.10  thinkbook16p gen5的声音问题已经被上游修复了，理论上升级到6.10版本即可

**Comment by sanruby77** [comment]
非常感谢,这段时间有需要的时候都是蓝牙音箱来处理,后面试试.

**Comment by YageGeng** [comment]
您好，我最近又转回Linux了，测试了下在最新的6.12 内核上 thinkbook 16p Gen5的声音还是有些问题（不能调节大小）我又修了一下。目前已经打了一个包传到aur了 legion-thinkbook16p-gen5-sound-fix-dkms，仓库的patch也更新了，有兴趣您可以再尝试一下。

**Comment by YageGeng** [comment]
> 非常感谢,这段时间有需要的时候都是蓝牙音箱来处理,后面试试.

您好，我最近又转回Linux了，测试了下在最新的6.12 内核上 thinkbook 16p Gen5的声音还是有些问题（不能调节大小）我又修了一下。目前已经打了一个包传到aur了 legion-thinkbook16p-gen5-sound-fix-dkms，仓库的patch也更新了，有兴趣您可以再尝试一下

**Comment by ayasa520** [comment]
非常感谢, 对我工作
